### ISSUE TITLE
Add a tutorial for distributed inference

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/lightning-tutorials#100]
## 🚀 Feature

[Users are asking for examples](https://github.com/PyTorchLightning/pytorch-lightning/discussions/5788) how to predict with models in a distributed setting. 

### Motivation

We could link such a tutorial in the PL main docs. 

### Pitch

Add tutorial page for prediction on single GPU, multiple GPU / multiple nodes. 
It should cover the PredictionWriterCallback and how to use it.

### Alternatives

-

### Additional context

Related PR #52

**Comment by gianscarpe** [comment]
Just pointing out a useful and elegant solution to multi-gpu prediction (does not involve creating new files)
https://github.com/open-mmlab/mmdetection/blob/482f60fe55c364e50e4fc4b50893a25d8cc261b0/mmdet/apis/test.py#L160

**Comment by allanchan339** [comment]
@awaelchli 
Any update on how to gather all validation_step_outputs to a single device {rank 0} at validation_epoch_end for further metrics calculation? I have redirected from discussion https://github.com/PyTorchLightning/pytorch-lightning/discussions/5788 to here.
