### ISSUE TITLE
Some mathmatic equtions cannot be displayed

### ISSUE THREAD

**Issue by Freed-Wu** [PyTorchLightning/lightning-tutorials#109]
Such as
<https://pytorch-lightning.readthedocs.io/en/latest/notebooks/course_UvA-DL/13-contrastive-learning.html>

![image](https://user-images.githubusercontent.com/32936898/142215301-870174b2-043c-40df-ba56-39af40f57574.png)

**Comment by akihironitta** [comment]
@Freed-Wu Thank you for reporting this issue. As `lightning-tutorials` repo covers the section in the docs, I have transferred this issue here from PL repo.

**Comment by ashutoshml** [comment]
I can take a look at this.

**Comment by ashutoshml** [comment]
`lightning-tutorials` seems to be working well. https://pytorchlightning.github.io/lightning-tutorials/notebooks/course_UvA-DL/13-contrastive-learning.html

It's only the documentation on https://pytorch-lightning.readthedocs.io/en/latest/notebooks/course_UvA-DL/13-contrastive-learning.html which seems to be showing incorrect mathematics equations.

**Comment by Borda** [comment]
@ethanwharris any idea?

**Comment by ashutoshml** [comment]
I tried `make html`  on the current `pytorch-lightning` repo. It seems to be working fine. There is a small error with \mathbb{1} in the tutorial - Perhaps mathjax doesn't support it. Not sure why the two previously mentioned HTML pages show different renderings.
