### ISSUE TITLE
link to `Edit in Github` is broken

### ISSUE THREAD

**Issue by edgarriba** [PyTorchLightning/lightning-tutorials#26]
## 🐛 Bug

The link `Edit in Github` in the generated docs is broken

![image](https://user-images.githubusercontent.com/5157099/121663141-63a3e780-caa6-11eb-8908-4ab202408d64.png)

**Comment by Borda** [comment]
not sure if this is possible to solve as the link to gis correct, just GH is not able t propagate the link throw submodule
so for example this target file almost correct except the `notebooks` is a submodule
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/notebooks/starters/datamodules.ipynb
![image](https://user-images.githubusercontent.com/6035284/121769678-497d0e80-cb65-11eb-81c1-98848fe66316.png)

**Comment by edgarriba** [comment]
Hardcoded in style files?

**Comment by Borda** [comment]
not sure what you mean, the `Edit in Github` is generated for all files by sphinx template/extension

**Comment by Borda** [comment]
closing for now as this is dependent on target integrated docs and used sphinx template :rabbit:
