### ISSUE TITLE
define requirements for notebooks

### ISSUE THREAD

**Issue by daMichaelB** [PyTorchLightning/lightning-tutorials#32]
## 🐛 Bug

CIFAR-10 Baseline Example Notebook is failing on importing `torchvision` as it is not part of the requirements files.

### To Reproduce

Steps to reproduce the behaviour:

1. Go to https://mybinder.org
2. `mybinder` will start a fresh docker container with this repository and all requirements installed
3. Start the Cifar-10-baseline example.
4. `torchvision` fails to be imported

### Expected behavior

Add `torchvision` to the `requirements/default.txt`

**Comment by Borda** [comment]
requirements are set for each notebook meta-file, so for the CIFAR it is here https://github.com/PyTorchLightning/lightning-tutorials/blob/79e1490f5f86d0aa127557fa5e660c73f88fc69d/starters/cifar10-baseline/.meta.yml#L8-L10
otherwise, the main requirements will be too heavy even for simple examples or what is your suggestion?

**Comment by Borda** [comment]
> 3\. Start the Cifar-10-baseline example.

are you opening the python file or ipynb in `.notebooks` folder?

**Comment by Borda** [comment]
ok, I may found a middle ground, we can add an extra cell at beginning of each notebook which would pip install special requirements for the particular notebook :]

**Comment by daMichaelB** [comment]
Hey thank you for your fast feedback! i was using the `.py` file and was not aware of the `.meta.yml`. I just saw that you create the `.ipynb` files from `.py`, which is cool stuff! Thanks for your explanation and can also be closed from my side.

**Comment by Borda** [comment]
I think that you brought good point and I will add the extra cell, so if you use standard env you shall have it all installed and no delay... btw, do you know if mybinder.org can use your own/custom image? (thinking about #23)

**Comment by daMichaelB** [comment]
Ok i think that might be helpful to have that cell on top, thanks man! There is such a thing on mybinder.org (https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html) but i have not tested it on my own. I only want to point out that `mybinder` was really helpful to debug through the code within seconds - But the downside is there is no GPU.
