### ISSUE TITLE
Requirements not working in colab

### ISSUE THREAD

**Issue by SkafteNicki** [PyTorchLightning/lightning-tutorials#49]
### To Reproduce

1. Open any notebook in colab
2. The `torch>=1.6, <1.9` dependency gives the error "no such file or directory"
<img width="508" alt="Capture" src="https://user-images.githubusercontent.com/24896311/123520989-159cff80-d6b4-11eb-9d58-c169fb8291bb.PNG">

### Expected behavior

Running cell should install requirements

### Additional context

Putting it in a string seems to work, but then it complains about compatibility:
![billede](https://user-images.githubusercontent.com/24896311/123521077-b986ab00-d6b4-11eb-9f68-89d259311a29.png)

**Comment by Borda** [comment]
fixed by 34836002c5f375b0786d2ae293f8ee81eb6104c1
